app:
  name: "douyin"
  mod: "dev"
  port: 10000
  version: "v0.0.1"
log:
  level: "debug"
  filename: "web.log"
  max_size: 200
  max_age: 30
  max_backups: 7
  log_mode: "dev"
mysql:
  host: "43.143.231.157"
  port: 3306
  user: "user"
  password: "123456"
  dbname: "douyin"
  max_open_connections: 200
  max_idle_connections: 50
redis:
  host: "43.143.231.157"
  port: 6379
  password: "123456"
  db: 0
  pool_size: 100
